-- =====================================
-- 1. DATABASE TABLES SCHEMA FOR VIZHUTHUGAL
-- =====================================

-- EMPLOYEES
CREATE TABLE IF NOT EXISTS employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    contact VARCHAR(50) NOT NULL,
    department VARCHAR(100) NOT NULL,
    role VARCHAR(100) NOT NULL,
    joining_date VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ATTENDANCE
CREATE TABLE IF NOT EXISTS attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_name VARCHAR(255),
    check_in VARCHAR(100),
    check_out VARCHAR(100),
    work_done TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ALUMNI CORE ENGAGEMENT
CREATE TABLE IF NOT EXISTS core_engagements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    district VARCHAR(100) NOT NULL,
    block VARCHAR(100) NOT NULL,
    school_name VARCHAR(255) NOT NULL,
    school_type VARCHAR(100),
    school_category VARCHAR(100),
    engagement_type VARCHAR(100),
    other_engagement_type VARCHAR(255),
    alumni_count INTEGER DEFAULT 0,
    amount_collected INTEGER DEFAULT 0,
    proof_files TEXT DEFAULT '[]', -- Stores ProofFile[] base64/JSON string
    important_attendees TEXT,
    remarks TEXT,
    entered_by VARCHAR(255),
    entered_time VARCHAR(100),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- WHATSAPP GROUP ENGAGEMENT
CREATE TABLE IF NOT EXISTS whatsapp_engagements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_name VARCHAR(255) NOT NULL,
    district VARCHAR(100),
    block VARCHAR(100),
    school_type VARCHAR(100),
    school_category VARCHAR(100),
    group_formed VARCHAR(10) DEFAULT 'Yes',
    group_link VARCHAR(500),
    member_count INTEGER DEFAULT 0,
    last_shared_message TEXT,
    last_shared_message_date VARCHAR(50),
    last_msg_responses TEXT,
    activity_status VARCHAR(50),
    changes_count INTEGER DEFAULT 0,
    history_json TEXT DEFAULT '[]', -- Stores history log JSON string
    entered_by VARCHAR(255),
    entered_time VARCHAR(100),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ALUMNI COMMUNITY REGISTRY (School Community)
CREATE TABLE IF NOT EXISTS school_communities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    district VARCHAR(100) NOT NULL,
    block VARCHAR(100) NOT NULL,
    school_name VARCHAR(255) NOT NULL,
    school_type VARCHAR(100),
    school_category VARCHAR(100),
    hm_supportive VARCHAR(10) DEFAULT 'No',
    smc_alumni_count INTEGER DEFAULT 0,
    ambassador_alumni_count INTEGER DEFAULT 0,
    approach_taken VARCHAR(255),
    period_started VARCHAR(50),
    period_ended VARCHAR(50),
    mobilized_count INTEGER DEFAULT 0,
    mobilized_status VARCHAR(10),
    alumni_group_platforms TEXT DEFAULT '[]', -- Stores JSON string
    other_platform VARCHAR(255),
    platform_link VARCHAR(500),
    risk_challenge TEXT,
    mitigation_taken TEXT,
    take_back TEXT,
    proof_files TEXT DEFAULT '[]', -- Stores JSON string
    media_content TEXT,
    celebrated_status VARCHAR(10) DEFAULT 'No',
    entered_by VARCHAR(255),
    entered_time VARCHAR(100),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ALUMNI CORE TEAM FORMATION
CREATE TABLE IF NOT EXISTS core_team_formations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    district VARCHAR(100) NOT NULL,
    block VARCHAR(100) NOT NULL,
    school_name VARCHAR(255) NOT NULL,
    school_type VARCHAR(100),
    school_category VARCHAR(100),
    hm_supportive VARCHAR(10) DEFAULT 'No',
    smc_alumni_support VARCHAR(10) DEFAULT 'No',
    ambassador_alumni_support VARCHAR(10) DEFAULT 'No',
    approach_taken VARCHAR(255),
    period_started VARCHAR(50),
    period_ended VARCHAR(50),
    core_team_count INTEGER DEFAULT 0,
    core_team_status VARCHAR(50),
    core_team_platforms TEXT DEFAULT '[]', -- Stores JSON string
    other_platform VARCHAR(255),
    platform_link VARCHAR(500),
    risk_challenge TEXT,
    mitigation_taken TEXT,
    take_back TEXT,
    proof_files TEXT DEFAULT '[]', -- Stores JSON string
    media_content TEXT,
    celebrated_status VARCHAR(10) DEFAULT 'No',
    entered_by VARCHAR(255),
    entered_time VARCHAR(100),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);


-- =====================================
-- 2. ENABLE REALTIME SYNC (SQL Notify)
-- =====================================
-- Ensure the publication 'supabase_realtime' exists.
-- It is usually created automatically by Supabase, but doing this prevents failure in a clean DB.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    CREATE PUBLICATION supabase_realtime;
  END IF;
EXCEPTION WHEN OTHERS THEN
  -- Handle permission or other issues gracefully
  NULL;
END $$;
-- Set the tables for the publication (this overrides/sets the list idempotently)
ALTER PUBLICATION supabase_realtime SET TABLE employees, attendance, core_engagements, whatsapp_engagements, school_communities, core_team_formations;


-- =====================================
-- 3. POPULATE INITIAL MOCK RECORDS
-- =====================================

-- Seed Employees
INSERT INTO employees (name, email, contact, department, role, joining_date)
VALUES 
('State Admin', 'admin@gmail.com', '9876543210', 'Management', 'Admin', '2026-06-01')
ON CONFLICT (email) DO NOTHING;

-- Seed WhatsApp Engagements
INSERT INTO whatsapp_engagements (school_name, district, block, school_type, school_category, group_formed, group_link, member_count, last_shared_message, last_shared_message_date, last_msg_responses, activity_status, changes_count, history_json, entered_by, entered_time)
VALUES
('Govt Hr Sec School, Madurai', 'Madurai', 'Madurai East', 'High Sec School', 'Centinary School', 'Yes', 'https://chat.whatsapp.com/GHSSAlumniMadurai2025', 245, 'Invitation for centenary fundraising meeting on June 15th.', '2026-06-01', '12 members clicked join, 5 sent RSVPs directly.', 'High', 0, '[]', 'Admin', '2026-06-01, 10:00:00 AM'),
('St. Mary''s School, Trichy', 'Tiruchirappalli', 'Thiruverumbur', 'Middle School', 'Vetri Palligal School', 'Yes', 'https://chat.whatsapp.com/StMarysAlumniTrichy', 480, 'Announced the new SMC mentoring session timetable.', '2026-06-02', '22 members confirmed availability, 2 asked for rescheduling.', 'High', 0, '[]', 'Manager', '2026-06-02, 11:30:00 AM'),
('Municipal Boys High School, Salem', 'Salem', 'Salem South', 'High School', 'Career Guidance', 'No', 'https://chat.whatsapp.com/SalemBoysHighAlumni', 0, 'N/A - Group is being set up', '2026-06-03', 'N/A', 'Low', 0, '[]', 'Karthik', '2026-06-03, 04:15:00 PM');

-- Seed Core Engagements
INSERT INTO core_engagements (district, block, school_name, school_type, school_category, engagement_type, alumni_count, amount_collected, proof_files, important_attendees, remarks, entered_by, entered_time)
VALUES
('Madurai', 'Madurai East', 'Govt Hr Sec School, Madurai', 'High Sec School', 'Centinary School', 'Alumni Meet', 45, 25000, '[]', 'District Collector, School Headmaster, SMC President', 'Discussed centenary celebration funding and sports ground expansion plans.', 'Admin', '2026-06-01, 10:00:00 AM'),
('Tiruchirappalli', 'Thiruverumbur', 'St. Joseph''s Middle School', 'Middle School', 'Vetri Palligal School', 'Career Guidance Session', 12, 0, '[]', 'IT Professional Alumni Lead, local teachers', 'Interactive guidance on computer science careers for 8th-grade students.', 'Manager', '2026-06-02, 11:30:00 AM'),
('Salem', 'Salem South', 'Municipal Boys High School', 'High School', 'Career Guidance', 'Others', 30, 120000, '[]', 'Alumni Association President, local business sponsors', 'Raised funds to upgrade classroom projectors and install high-speed internet.', 'Karthik', '2026-06-03, 04:15:00 PM');
