export const DISTRICTS = [
  "Ariyalur", "Chengalpattu", "Chennai", "Coimbatore", "Cuddalore", "Dharmapuri", "Dindigul", "Erode", "Kallakurichi", "Kanchipuram", "Kanniyakumari", "Karur", "Krishnagiri", "Madurai", "Mayiladuthurai", "Nagapattinam", "Namakkal", "Nilgiris", "Perambalur", "Pudukkottai", "Ramanathapuram", "Ranipet", "Salem", "Sivaganga", "Tenkasi", "Thanjavur", "Theni", "Thoothukudi", "Tiruchirappalli", "Tirunelveli", "Tirupathur", "Tiruppur", "Tiruvallur", "Tiruvannamalai", "Tiruvarur", "Vellore", "Viluppuram", "Virudhunagar"
];

export const DISTRICT_BLOCKS: Record<string, string[]> = {
  Ariyalur: [
    "Andimadam",
    "Ariyalur",
    "Jayankondam",
    "Sendurai",
    "T. Palur",
    "Thirumanur"
  ],
  Chengalpattu: [
    "Acharapakkam",
    "Chithamur",
    "Kattankolathur",
    "Lathur",
    "Madurantakam",
    "St. Thomas Mount",
    "Thiruporur",
    "Tirukkalukundram"
  ],
  Chennai: [
    "Madhavaram",
    "Puzhal",
    "Sholinganallur"
  ],
  Coimbatore: [
    "Anaimalai",
    "Annur",
    "Karamadai",
    "Kinathukadavu",
    "Madukkarai",
    "Periyanaickenpalayam",
    "Pollachi North",
    "Pollachi South",
    "Sarcarsamakulam",
    "Sulur",
    "Sultanpet",
    "Thondamuthur"
  ],
  Cuddalore: [
    "Annagramam",
    "Cuddalore",
    "Kammapuram",
    "Kattumannarkoil",
    "Keerapalayam",
    "Komaratchi",
    "Kurinjipadi",
    "Mangalur",
    "Melbhuvanagiri",
    "Nallur",
    "Panruti",
    "Parangipettai",
    "Srimushnam",
    "Vriddhachalam"
  ],
  Dharmapuri: [
    "Dharmapuri",
    "Harur",
    "Karimangalam",
    "Morappur",
    "Nallampalli",
    "Palacode",
    "Pappireddipatti",
    "Pennagaram"
  ],
  Dindigul: [
    "Athoor",
    "Dindigul",
    "Gujiliamparai",
    "Kodaikanal",
    "Natham",
    "Nilakottai",
    "Oddanchatram",
    "Palani",
    "Reddiyarchatram",
    "Shanarpatti",
    "Thoppampatti",
    "Vadamadurai",
    "Vattalkundu",
    "Vedasandur"
  ],
  Erode: [
    "Ammapet",
    "Anthiyur",
    "Bhavani",
    "Bhavanisagar",
    "Chennimalai",
    "Erode",
    "Gobichettipalayam",
    "Kodumudi",
    "Modakurichi",
    "Nambiyur",
    "Perundurai",
    "Sathyamangalam",
    "Thalavadi"
  ],
  Kallakurichi: [
    "Chinnasalem",
    "Kallakurichi",
    "Kalrayan Hills",
    "Rishivandiyam",
    "Sankarapuram",
    "Thiyagadurgam",
    "Tirukoilur",
    "Ulundurpet"
  ],
  Kanchipuram: [
    "Kanchipuram",
    "Kundrathur",
    "Sriperumbudur",
    "Uthiramerur",
    "Walajabad"
  ],
  Karur: [
    "Aravakurichi",
    "K.Paramathi",
    "Karur",
    "Krishnarayapuram",
    "Kulithalai",
    "Thanthoni",
    "Thogaimalai",
    "Kadavur"
  ],
  Kanniyakumari: [
    "Agastheeswaram",
    "Killiyoor",
    "Kurunthancode",
    "Melpuram",
    "Munchirai",
    "Rajakkamangalam",
    "Thackalay",
    "Thiruvattar",
    "Thovalai"
  ],
  Krishnagiri: [
    "Bargur",
    "Hosur",
    "Kaveripattinam",
    "Kelamangalam",
    "Krishnagiri",
    "Mathur",
    "Shoolagiri",
    "Thally",
    "Uthangarai",
    "Veppanapalli"
  ],
  Madurai: [
    "Alanganallur",
    "Chellampatti",
    "Kallikudi",
    "Kottampatti",
    "Madurai East",
    "Madurai West",
    "Melur",
    "Sedapatti",
    "Thirumangalam",
    "Thiruparankundram",
    "Usilampatti",
    "Vadipatti"
  ],
  Mayiladuthurai: [
    "Kollidam",
    "Kuthalam",
    "Mayiladuthurai",
    "Sembanarkoil",
    "Sirkazhi"
  ],
  Nagapattinam: [
    "Keelaiyur",
    "Kilvelur",
    "Nagapattinam",
    "Thalainayar",
    "Thirumarugal",
    "Vedaranyam"
  ],
  Namakkal: [
    "Elachipalayam",
    "Erumapatty",
    "Kabilarmalai",
    "Kolli Hills",
    "Mallasamudram",
    "Mohanur",
    "Namagiripet",
    "Namakkal",
    "Pallipalayam",
    "Paramathi",
    "Puduchatram",
    "Rasipuram",
    "Sendamangalam",
    "Tiruchengode",
    "Vennandur"
  ],
  Nilgiris: [
    "Coonoor",
    "Gudalur",
    "Kotagiri",
    "Kundah",
    "Udhagamandalam"
  ],
  Perambalur: [
    "Alathur",
    "Perambalur",
    "Veppanthattai",
    "Veppur"
  ],
  Pudukkottai: [
    "Annavasal",
    "Aranthangi",
    "Arimalam",
    "Avudayarkoil",
    "Gandarvakottai",
    "Karambakudi",
    "Kunnandarkoil",
    "Manamelkudi",
    "Ponnamaravathi",
    "Pudukkottai",
    "Thiruvarankulam",
    "Viralimalai"
  ],
  Ramanathapuram: [
    "Bogalur",
    "Kadaladi",
    "Kamuthi",
    "Mandapam",
    "Mudukulathur",
    "Nainarkoil",
    "Paramakudi",
    "Rajasingamangalam",
    "Ramanathapuram",
    "Tiruppullani"
  ],
  Ranipet: [
    "Arcot",
    "Arakkonam",
    "Nemili",
    "Sholinghur",
    "Timiri",
    "Walajah"
  ],
  Salem: [
    "Attur",
    "Ayothiapattinam",
    "Gangavalli",
    "Idappadi",
    "Kadayampatti",
    "Konganapuram",
    "Kolathur",
    "Mecheri",
    "Nangavalli",
    "Omalur",
    "Peddanaickenpalayam",
    "Salem",
    "Sankari",
    "Thalaivasal",
    "Valapady",
    "Veerapandi",
    "Yercaud"
  ],
  Sivaganga: [
    "Devakottai",
    "Ilayangudi",
    "Kalaiyarkovil",
    "Kallal",
    "Kannangudi",
    "Manamadurai",
    "S.Pudur",
    "Sakkottai",
    "Singampunari",
    "Sivaganga",
    "Tiruppathur"
  ],
  Tenkasi: [
    "Alangulam",
    "Kadayanallur",
    "Keelapavoor",
    "Kuruvikulam",
    "Melaneelithanallur",
    "Sankarankovil",
    "Shencottah",
    "Tenkasi",
    "Vasudevanallur"
  ],
  Thanjavur: [
    "Ammapettai",
    "Budalur",
    "Kumbakonam",
    "Madukkur",
    "Orathanadu",
    "Papanasam",
    "Pattukkottai",
    "Peravurani",
    "Sethubavachatram",
    "Thanjavur",
    "Thiruvaiyaru",
    "Thiruvidaimarudur"
  ],
  Theni: [
    "Andipatti",
    "Bodinayakanur",
    "Chinnamanur",
    "K.Myladumparai",
    "Periyakulam",
    "Theni",
    "Uthamapalayam"
  ],
  Thoothukudi: [
    "Alwarthirunagari",
    "Karungulam",
    "Kayathar",
    "Kovilpatti",
    "Ottapidaram",
    "Pudur",
    "Sathankulam",
    "Srivaikundam",
    "Thiruchendur",
    "Thoothukudi",
    "Udangudi",
    "Vilathikulam"
  ],
  Tiruchirappalli: [
    "Andanallur",
    "Lalgudi",
    "Manachanallur",
    "Manapparai",
    "Marungapuri",
    "Musiri",
    "Pullambadi",
    "Thathaiyangarpettai",
    "Thiruverumbur",
    "Thottiam",
    "Turaiyur",
    "Uppiliyapuram",
    "Vaiyampatti"
  ],
  Tirunelveli: [
    "Ambasamudram",
    "Cheranmahadevi",
    "Kalakkad",
    "Manur",
    "Nanguneri",
    "Palayamkottai",
    "Pappakudi",
    "Radhapuram"
  ],
  Tirupathur: [
    "Alangayam",
    "Jolarpet",
    "Kandili",
    "Madhanur",
    "Natrampalli",
    "Tirupathur"
  ],
  Tiruppur: [
    "Avanashi",
    "Dharapuram",
    "Kangeyam",
    "Kundadam",
    "Madathukulam",
    "Palladam",
    "Pongalur",
    "Tiruppur",
    "Udumalpet",
    "Uthukuli"
  ],
  Tiruvallur: [
    "Ellapuram",
    "Gummidipoondi",
    "Kadambathur",
    "Minjur",
    "Pallipattu",
    "Poonamallee",
    "Poondi",
    "R.K.Pet",
    "Sholavaram",
    "Tiruttani",
    "Tiruvallur",
    "Villivakkam"
  ],
  Tiruvannamalai: [
    "Arani",
    "Chetpet",
    "Chengam",
    "Jawadhu Hills",
    "Kalasapakkam",
    "Keelpennathur",
    "Polur",
    "Pudupalayam",
    "Thandrampattu",
    "Thellar",
    "Tiruvannamalai",
    "Vembakkam",
    "West Arani"
  ],
  Tiruvarur: [
    "Kodavasal",
    "Koradachery",
    "Kottur",
    "Mannargudi",
    "Muthupettai",
    "Nannilam",
    "Needamangalam",
    "Thiruthuraipoondi",
    "Tiruvarur",
    "Valangaiman"
  ],
  Vellore: [
    "Anaicut",
    "Gudiyatham",
    "K.V.Kuppam",
    "Katpadi",
    "Pernambut"
  ],
  Viluppuram: [
    "Gingee",
    "Kandamangalam",
    "Kanai",
    "Koliyanur",
    "Mailam",
    "Marapadi",
    "Melmalayanur",
    "Mugaiyur",
    "Olakkur",
    "Thiruvennainallur",
    "Ulundurpet",
    "Vallam",
    "Vanur",
    "Vikravandi"
  ],
  Virudhunagar: [
    "Aruppukottai",
    "Kariapatti",
    "Narikudi",
    "Rajapalayam",
    "Sattur",
    "Sivakasi",
    "Srivilliputhur",
    "Tiruchuli",
    "Vathirairuppu",
    "Virudhunagar",
    "Watrap"
  ]
};
